PTransito/Areas/AreaGestion/Controllers/FACTURAController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using TransitoModel;
using TransitoModel.ModelAux;
using TransitoServicio;

namespace PTransito.Areas.AreaGestion.Controllers
{
    public class FACTURAController : Controller
    {
        private PRUEBA1Entities db = new PRUEBA1Entities();
        private SERVICIO_FACTURA sf = new SERVICIO_FACTURA();

        public async Task<ActionResult> Index()
        {
            return View(await sf.FacturaListar());
        }

        public async Task<ActionResult> Details(decimal id)
        {
            var aux = await sf.FacturaDetalle(id);
            if (aux == null)
            {
                return HttpNotFound();
            }
            ViewBag.total = aux.FACTURA_TRAMITE.Sum(x => x.TRAMITE.VALOR);
            ViewBag.ID = new SelectList(db.TRAMITE, "ID", "DESCRIPCION");
            return View(aux);
        }

        public ActionResult Create()
        {
            ViewBag.contador = 0;
            ViewBag.ID_VEHICULO = new SelectList(db.VEHICULO, "ID", "PLACA");
            ViewBag.ID_TRAMITE = new SelectList(db.TRAMITE, "ID", "DESCRIPCION");
            return View("Create");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Buscar(ModFactura m)
        {
            ViewBag.contador = sf.Contar(m);
            ViewBag.ID_VEHICULO = new SelectList(db.VEHICULO.Where(x => x.PLACA == m.PLACA), "ID", "PLACA");
            ViewBag.ID = new SelectList(db.TRAMITE, "ID", "DESCRIPCION");

            return View("create");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AgregarTramite(ModFactura m)
        {
            if (await sf.AgregarTramite(m))
            {
                ViewBag.ID = new SelectList(db.TRAMITE, "ID", "DESCRIPCION");
                return RedirectToAction("Details", new { id = m.FACTURA.ID });
            }
            else
            {
                ViewBag.ID = new SelectList(db.TRAMITE, "ID", "DESCRIPCION");
                return RedirectToAction("Details", new { id = m.FACTURA.ID });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ModFactura m)
        {
            if (ModelState.IsValid)
            {
                decimal aux = await sf.CrearFactura(m);
                if (aux > 0)
                    return RedirectToAction("Details", new { id = aux });
            }
            return View("Buscar");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PTransito/Areas/AreaGestion/Views/FACTURA/Create.cshtml
@model TransitoModel.ModelAux.ModFactura

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>





@using (Html.BeginForm("Buscar", "FACTURA", FormMethod.Post))
{

    @Html.AntiForgeryToken()


    <div class="row">
        <p>
            Buscar placa:
            @Html.EditorFor(model => model.PLACA, new { htmlAttributes = new { @class = "form-control" } })
            <hr />
            @Html.EditorFor(model => model.DOCUMENTO, new { htmlAttributes = new { @class = "form-control" } })
        </p>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ASOCIAR" class="btn btn-default" />
            </div>
        </div>
    </div>

}


@if (@ViewBag.contador > 0)
{


    using (Html.BeginForm("Create", "FACTURA", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>FACTURA</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FACTURA.NUMERO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FACTURA.NUMERO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FACTURA.NUMERO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FACTURA.FECHA, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FACTURA.FECHA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FACTURA.FECHA, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FACTURA.ID_VEHICULO, "ID_VEHICULO", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.FACTURA.ID_VEHICULO, (SelectList)ViewBag.ID_VEHICULO, new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.FACTURA.ID_VEHICULO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FACTURA.OBSERVACIONES, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FACTURA.OBSERVACIONES, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FACTURA.OBSERVACIONES, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TRAMITE.ID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.TRAMITE.ID, (SelectList)ViewBag.ID, new { @class = "form-control" })

                    @Html.ValidationMessageFor(model => model.TRAMITE.ID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PTransito/Areas/AreaGestion/Views/FACTURA/Delete.cshtml
@model TransitoModel.FACTURA

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FACTURA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NUMERO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NUMERO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OBSERVACIONES)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OBSERVACIONES)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VEHICULO.PLACA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VEHICULO.PLACA)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PTransito/Areas/AreaGestion/Views/FACTURA/Details.cshtml
@model TransitoModel.ModelAux.ModFactura

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>FACTURA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FACTURA.NUMERO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FACTURA.NUMERO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FACTURA.FECHA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FACTURA.FECHA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FACTURA.OBSERVACIONES)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FACTURA.OBSERVACIONES)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FACTURA.VEHICULO.PLACA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FACTURA.VEHICULO.PLACA)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("retornar", "Index")
</p>

@using (Html.BeginForm("AgregarTramite", "FACTURA", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.FACTURA.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.TRAMITE.ID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TRAMITE.ID, (SelectList)ViewBag.ID, new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.TRAMITE.ID, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="ASOCIAR" class="btn btn-default" />
        </div>
    </div>

}


@if (Model.FACTURA_TRAMITE == null)
{
    <h4>Buscar placa</h4>
}
else
{

    <h3>Propietarios Vinculados</h3>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FACTURA_TRAMITE.FirstOrDefault().TRAMITE.DESCRIPCION)
            </th>
            <th align="center">
                @Html.DisplayNameFor(model => model.FACTURA_TRAMITE.FirstOrDefault().TRAMITE.VALOR)
            </th>

        </tr>

        @foreach (var item in Model.FACTURA_TRAMITE)
        {
            <tr>
                <td >
                    @Html.DisplayFor(modelItem => item.TRAMITE.DESCRIPCION)
                </td>
                <td align="center">
                    @Html.DisplayFor(modelItem => item.TRAMITE.VALOR)
                </td>
            </tr>
        }
        <tr>
            <td >
                <strong>Totals</strong>
            </td>
            <td align="center">
                <strong>@ViewBag.total</strong>
            </td>
        </tr>
    </table>



}

PTransito/Areas/AreaGestion/Views/FACTURA/Edit.cshtml
@model TransitoModel.FACTURA

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FACTURA</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NUMERO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NUMERO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NUMERO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_VEHICULO, "ID_VEHICULO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_VEHICULO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_VEHICULO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OBSERVACIONES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OBSERVACIONES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OBSERVACIONES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PTransito/Areas/AreaGestion/Views/FACTURA/Index.cshtml
@model IEnumerable<TransitoModel.FACTURA>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NUMERO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FECHA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OBSERVACIONES)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VEHICULO.PLACA)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NUMERO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FECHA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OBSERVACIONES)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VEHICULO.PLACA)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
        </td>
    </tr>
}

</table>